# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/baywheels',
                'doc_host': 'https://patrickod.github.io',
                'git_url': 'https://github.com/patrickod/baywheels',
                'lib_path': 'baywheels'},
  'syms': {'baywheels.core': {'baywheels.core.foo': ('core.html#foo', 'baywheels/core.py')}}}
